model = "gpt-5.3-codex"
model_reasoning_effort = "medium"

[tools]
web_search = true

[mcp]

[mcp_servers.ipr-rpi-dev-ssh]
command = "npx"
args = [
    "-y",
    "@fangjunjie/ssh-mcp-server",
    "--host",
    "ipr-dev-pi4",
    "--port",
    "22",
    "--username",
    "meibye",
    "--privateKey",
    "C:/Users/micha/.ssh/id_ed25519_ipr_kb",
    "--blacklist",
    "^rm .*,^shutdown.*,^reboot.*",
]
