#!/usr/bin/env bash
#
# 07_show_info.sh
#
# Purpose:
#   Display the most important information the user needs after provisioning:
#   hotspot SSID and password, web dashboard URL, SSH access, and Bluetooth name.
#
#   Hotspot credentials are read from /etc/ipr-hotspot.secret (written by
#   04_enable_services.sh or ipr-provision.sh on first run).  Run this script
#   at any time to display the current credentials.
#
# Usage:
#   sudo ./provision/07_show_info.sh
#
# Prerequisites:
#   - /opt/ipr_common.env (populated by earlier provisioning steps)
#
# category: Provisioning
# purpose: Display post-provisioning summary (credentials, URLs, SSH access)
# sudo: recommended

set -euo pipefail

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Error: this script must be run as root. Use: sudo $0" >&2
  exit 1
fi

BOLD='\033[1m'
GREEN='\033[0;32m'
BLUE='\033[1;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# Load environment (best-effort)
ENV_FILE="/opt/ipr_common.env"
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

BT_DEVICE_NAME="${BT_DEVICE_NAME:-IPR Keyboard}"
AP_SSID_PREFIX="${AP_SSID_PREFIX:-ipr-setup}"
REPO_DIR="${REPO_DIR:-/home/meibye/dev/ipr-keyboard}"
APP_USER="${APP_USER:-meibye}"

# ── Hotspot credentials ───────────────────────────────────────────────────────
# Read from /etc/ipr-hotspot.secret (generated by ipr-provision.sh or
# 04_enable_services.sh).  Fall back gracefully if the file is absent.
SECRET_FILE="/etc/ipr-hotspot.secret"
HOTSPOT_SSID=""
HOTSPOT_PASS=""
if [[ -f "$SECRET_FILE" ]]; then
  HOTSPOT_SSID=$(grep '^SSID=' "$SECRET_FILE" | cut -d= -f2-)
  HOTSPOT_PASS=$(grep '^PASS=' "$SECRET_FILE" | cut -d= -f2-)
fi
if [[ -z "$HOTSPOT_SSID" ]]; then
  HOTSPOT_SSID="(not yet generated — run ipr-provision.sh first)"
fi
if [[ -z "$HOTSPOT_PASS" ]]; then
  HOTSPOT_PASS="(not yet generated — run ipr-provision.sh first)"
fi

# ── Network ───────────────────────────────────────────────────────────────────
DEVICE_HOSTNAME=$(hostname 2>/dev/null || echo "unknown")
MDNS_NAME="${DEVICE_HOSTNAME}.local"
CURRENT_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "")

# ── Dashboard port (read from config.json, fall back to default) ──────────────
DASHBOARD_PORT=8080
CONFIG_JSON="${REPO_DIR}/config.json"
if [[ -f "$CONFIG_JSON" ]] && command -v python3 &>/dev/null; then
  DASHBOARD_PORT=$(python3 -c \
    "import json; d=json.load(open('${CONFIG_JSON}')); print(d.get('LogPort', 8080))" \
    2>/dev/null || echo 8080)
fi

# The dashboard serves HTTPS; drop the port suffix on the standard 443.
_PORT_SUFFIX=":${DASHBOARD_PORT}"
[[ "$DASHBOARD_PORT" == "443" ]] && _PORT_SUFFIX=""
if [[ -n "$CURRENT_IP" ]]; then
  DASHBOARD_URL="https://${CURRENT_IP}${_PORT_SUFFIX}/"
else
  DASHBOARD_URL="https://<device-ip>${_PORT_SUFFIX}/"
fi
DASHBOARD_MDNS_URL="https://${MDNS_NAME}${_PORT_SUFFIX}/"

# Initial admin password — written by the app on first start, removed when
# the admin password is changed in the dashboard.
ADMIN_PWD_FILE="${REPO_DIR}/admin_initial_password.txt"
ADMIN_INITIAL_PWD=""
[[ -r "$ADMIN_PWD_FILE" ]] && ADMIN_INITIAL_PWD="$(tr -d '\r\n' < "$ADMIN_PWD_FILE")"

# ── Print summary ─────────────────────────────────────────────────────────────
echo ""
echo -e "${BLUE}${BOLD}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}${BOLD}║         IPR Keyboard — Device Information        ║${NC}"
echo -e "${BLUE}${BOLD}╚══════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${CYAN}${BOLD}── Bluetooth ──────────────────────────────────────────${NC}"
echo -e "  Device name  : ${BOLD}${BT_DEVICE_NAME}${NC}"
echo -e "  Pairing      : Search for '${BT_DEVICE_NAME}' on the host device"
echo ""

echo -e "${CYAN}${BOLD}── Wi-Fi Management Hotspot (on demand: magnet 3 s) ───${NC}"
echo -e "  SSID         : ${BOLD}${HOTSPOT_SSID}${NC}"
echo -e "  Password     : ${BOLD}${HOTSPOT_PASS}${NC}"
echo -e "  Setup URL    : ${BOLD}https://10.42.0.1/setup/${NC}"
echo -e "  Web UI login : ${BOLD}ipr${NC} / ${BOLD}${HOTSPOT_PASS}${NC}"
echo ""

echo -e "${CYAN}${BOLD}── Web Dashboard ──────────────────────────────────────${NC}"
echo -e "  By IP        : ${BOLD}${DASHBOARD_URL}${NC}"
echo -e "  By mDNS      : ${BOLD}${DASHBOARD_MDNS_URL}${NC}"
if [[ -n "$ADMIN_INITIAL_PWD" ]]; then
  echo -e "  Login        : ${BOLD}admin${NC} / ${BOLD}${ADMIN_INITIAL_PWD}${NC}"
  echo -e "                 (initial password — change it in the dashboard; this line"
  echo -e "                  and admin_initial_password.txt then disappear)"
elif [[ -f "${REPO_DIR}/users.json" ]]; then
  echo -e "  Login        : ${BOLD}admin${NC} / the password set in the dashboard"
else
  echo -e "  Login        : admin / generated at first start of ipr_keyboard.service"
  echo -e "                 (re-run this script, or see the setup portal home page)"
fi
echo ""

echo -e "${CYAN}${BOLD}── SSH Access ─────────────────────────────────────────${NC}"
if [[ -n "$CURRENT_IP" ]]; then
  echo -e "  By IP        : ${BOLD}ssh ${APP_USER}@${CURRENT_IP}${NC}"
fi
echo -e "  By mDNS      : ${BOLD}ssh ${APP_USER}@${MDNS_NAME}${NC}"
echo ""

echo -e "${CYAN}${BOLD}── Device ─────────────────────────────────────────────${NC}"
echo -e "  Hostname     : ${BOLD}${DEVICE_HOSTNAME}${NC}"
echo ""

echo -e "${GREEN}${BOLD}Provisioning complete. Device is ready for use.${NC}"
echo ""
