#!/usr/bin/env bash
#
# Install Copilot/MCP debug tools and configure environment for remote diagnostics
#
# Usage:
#   sudo ./scripts/rpi-debug/install_dbg_tools.sh \
#     --ble-service bt_hid_ble.service \
#     --agent-service bt_hid_agent_unified.service \
#     --hci hci0 \
#     --log-root /var/log/ipr \
#     --copilot-user copilotdiag \
#     --copilot-repo /home/copilotdiag/ipr-keyboard
#
# Prerequisites:
#   - Must be run as root (uses sudo)
#
# category: Debug
# purpose: Install debugging tools and configure environment for Copilot/MCP diagnostics
# parameters: --ble-service,--agent-service,--hci,--log-root,--copilot-user,--copilot-repo
# sudo: yes
#
set -euo pipefail

# -----------------------------
# Defaults
# -----------------------------
# Source common environment
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/dbg_common.env"

usage() {
  cat <<'EOF'
Usage:
  sudo ./scripts/rpi-debug/install_dbg_tools.sh [options]

Options:
  --ble-service <unit>     BLE HID service unit (default: bt_hid_ble.service)
  --agent-service <unit>   Unified agent service unit (default: bt_hid_agent_unified.service)
  --hci <dev>              HCI device name (default: hci0)
  --log-root <dir>         Debug log root (default: /var/log/ipr)
  --copilot-user <user>    Copilot/MCP SSH user for sudoers (default: copilotdiag)
  --copilot-repo <dir>     Repo directory to store in /etc/ipr_dbg.env (default: repo root)
  --sudoers <path>         Sudoers file path (default: /etc/sudoers.d/<user>-ipr-dbg)
  -h, --help               Show this help
EOF
}

# -----------------------------
# Arg parsing
# -----------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --ble-service)   BLE_SERVICE="$2"; shift 2 ;;
    --agent-service) AGENT_SERVICE="$2"; shift 2 ;;
    --hci)           HCI="$2"; shift 2 ;;
    --log-root)      LOG_ROOT="$2"; shift 2 ;;
    --copilot-user)  COPILOT_USER="$2"; shift 2 ;;
    --copilot-repo)  COPILOT_REPO="$2"; shift 2 ;;
    --sudoers)       SUDOERS_FILE="$2"; shift 2 ;;
    -h|--help)       usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: Run as root (sudo)." >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [[ -z "$COPILOT_REPO" ]]; then
  COPILOT_REPO="$REPO_ROOT"
fi

if [[ -z "$SUDOERS_FILE" ]]; then
  SUDOERS_FILE="/etc/sudoers.d/${COPILOT_USER}-ipr-dbg"
fi

# -----------------------------
# Basic validation
# -----------------------------
required_files=(
  "$SCRIPT_DIR/dbg_common.env"
  "$SCRIPT_DIR/dbg_deploy.sh"
  "$SCRIPT_DIR/dbg_diag_bundle.sh"
  "$SCRIPT_DIR/dbg_pairing_capture.sh"
  "$SCRIPT_DIR/dbg_bt_restart.sh"
  "$SCRIPT_DIR/dbg_bt_soft_reset.sh"
  "$SCRIPT_DIR/dbg_bt_bond_wipe.sh"
  "$SCRIPT_DIR/dbg_stack_status.sh"
)

missing=0
for f in "${required_files[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "ERROR: Missing required file: $f" >&2
    missing=1
  fi
done
if [[ "$missing" -ne 0 ]]; then
  exit 1
fi

# -----------------------------
# Ensure log root exists
# -----------------------------
mkdir -p "$LOG_ROOT"
chown root:adm "$LOG_ROOT" || true
chmod 2775 "$LOG_ROOT" || true

# -----------------------------
# Install scripts to /usr/local/bin
# -----------------------------
install -m 0755 "$SCRIPT_DIR/dbg_common.env"         /usr/local/bin/dbg_common.env
install -m 0755 "$SCRIPT_DIR/dbg_deploy.sh"          /usr/local/bin/dbg_deploy.sh
install -m 0755 "$SCRIPT_DIR/dbg_diag_bundle.sh"     /usr/local/bin/dbg_diag_bundle.sh
install -m 0755 "$SCRIPT_DIR/dbg_pairing_capture.sh" /usr/local/bin/dbg_pairing_capture.sh
install -m 0755 "$SCRIPT_DIR/dbg_bt_restart.sh"      /usr/local/bin/dbg_bt_restart.sh
install -m 0755 "$SCRIPT_DIR/dbg_bt_soft_reset.sh"   /usr/local/bin/dbg_bt_soft_reset.sh
install -m 0755 "$SCRIPT_DIR/dbg_bt_bond_wipe.sh"    /usr/local/bin/dbg_bt_bond_wipe.sh
install -m 0755 "$SCRIPT_DIR/dbg_stack_status.sh"    /usr/local/bin/dbg_stack_status.sh

# -----------------------------
# Write /etc/ipr_dbg.env (single source of truth)
# -----------------------------
DBG_ENV="/etc/ipr_dbg.env"
cat > "$DBG_ENV" <<EOF
# Auto-generated by install_dbg_tools.sh
DBG_BLE_SERVICE="${BLE_SERVICE}"
DBG_AGENT_SERVICE="${AGENT_SERVICE}"
DBG_HCI="${HCI}"
DBG_LOG_ROOT="${LOG_ROOT}"
DBG_COPILOT_REPO="${COPILOT_REPO}"
EOF
chmod 0644 "$DBG_ENV"

# -----------------------------
# Configure sudoers whitelist
# -----------------------------
cat > "$SUDOERS_FILE" <<EOF
${COPILOT_USER} ALL=(root) NOPASSWD: \
  /usr/local/bin/dbg_deploy.sh, \
  /usr/local/bin/dbg_diag_bundle.sh, \
  /usr/local/bin/dbg_pairing_capture.sh *, \
  /usr/local/bin/dbg_bt_restart.sh, \
  /usr/local/bin/dbg_bt_soft_reset.sh, \
  /usr/local/bin/dbg_bt_bond_wipe.sh *, \
  /usr/local/bin/dbg_stack_status.sh, \
  /usr/bin/systemctl restart bluetooth, \
  /usr/bin/systemctl start bluetooth, \
  /usr/bin/systemctl stop bluetooth, \
  /usr/bin/systemctl restart ${AGENT_SERVICE}, \
  /usr/bin/systemctl start ${AGENT_SERVICE}, \
  /usr/bin/systemctl stop ${AGENT_SERVICE}, \
  /usr/bin/systemctl restart ${BLE_SERVICE}, \
  /usr/bin/systemctl start ${BLE_SERVICE}, \
  /usr/bin/systemctl stop ${BLE_SERVICE}, \
  /usr/bin/journalctl -u bluetooth *, \
  /usr/bin/journalctl -u ${AGENT_SERVICE} *, \
  /usr/bin/journalctl -u ${BLE_SERVICE} *, \
  /usr/bin/btmgmt *
EOF

visudo -cf "$SUDOERS_FILE"

# -----------------------------
# Output summary
# -----------------------------
echo "Installed dbg tools to /usr/local/bin:"
echo "  dbg_common.env"
echo "  dbg_deploy.sh"
echo "  dbg_diag_bundle.sh"
echo "  dbg_pairing_capture.sh"
echo "  dbg_bt_restart.sh"
echo "  dbg_bt_soft_reset.sh"
echo "  dbg_bt_bond_wipe.sh"
echo "  dbg_stack_status.sh"
echo
echo "Wrote:"
echo "  $DBG_ENV"
echo "  $SUDOERS_FILE"
echo
echo "Config:"
echo "  BLE_SERVICE   = $BLE_SERVICE"
echo "  AGENT_SERVICE = $AGENT_SERVICE"
echo "  HCI           = $HCI"
echo "  LOG_ROOT      = $LOG_ROOT"
echo "  COPILOT_REPO  = $COPILOT_REPO"
echo
echo "Next:"
echo "  sudo dbg_stack_status.sh"
echo "  sudo dbg_pairing_capture.sh 60"
