#!/usr/bin/env bash
#
# svc_install_bt_hid_agent.sh
#
# Installs the bt_hid_agent service and script.
# This service provides Bluetooth pairing and authorization.
#
# Usage:
#   sudo ./scripts/service/svc_install_bt_hid_agent.sh
#
# Prerequisites:
#   - Must be run as root (uses sudo)
#
# category: Service
# purpose: Install Bluetooth HID agent service for pairing
#

set -eo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Please run as root: sudo $0"
  exit 1
fi

AGENT_PATH="/usr/local/bin/bt_hid_agent.py"

echo "=== [svc_install_bt_hid_agent] Installing bt_hid_agent service ==="

########################################
# Create Bluetooth agent script
########################################
echo "=== [svc_install_bt_hid_agent] Writing $AGENT_PATH ==="
cat > "$AGENT_PATH" << 'EOF'
#!/usr/bin/env python3
"""
bt_hid_agent.py

BlueZ Agent for ipr-keyboard.

Responsibilities:
    - Register as org.bluez.Agent1 with capability "KeyboardOnly"
    - Set adapter Powered/Discoverable/Pairable on startup
    - Auto-accept passkey confirmation and service authorization
"""

from __future__ import annotations

import sys
import dbus
import dbus.mainloop.glib
import dbus.service
from gi.repository import GLib

try:
        from systemd import journal
except ImportError:
        class DummyJournal:
                @staticmethod
                def send(msg, **kwargs):
                        print(msg)
        journal = DummyJournal()

BLUEZ_SERVICE_NAME = "org.bluez"
AGENT_IFACE = "org.bluez.Agent1"
AGENT_MANAGER_IFACE = "org.bluez.AgentManager1"
ADAPTER_IFACE = "org.bluez.Adapter1"
DBUS_PROP_IFACE = "org.freedesktop.DBus.Properties"

AGENT_PATH = "/org/bluez/agent/ipr_keyboard"


def _find_adapter(bus: dbus.bus.BusConnection) -> str:
        obj = bus.get_object(BLUEZ_SERVICE_NAME, "/")
        om = dbus.Interface(obj, "org.freedesktop.DBus.ObjectManager")
        objects = om.GetManagedObjects()
        for path, ifaces in objects.items():
                if ADAPTER_IFACE in ifaces:
                        return path
        return ""


class IprKeyboardAgent(dbus.service.Object):
        def __init__(self, bus: dbus.bus.BusConnection) -> None:
                super().__init__(bus, AGENT_PATH)
                self._generated_passkey = None

        # Most of these just "always-yes" or log and continue.
        @dbus.service.method(AGENT_IFACE, in_signature="o", out_signature="")
        def Release(self, device) -> None:
                journal.send("[agent] Release called")

        @dbus.service.method(AGENT_IFACE, in_signature="o", out_signature="s")
        def RequestPinCode(self, device) -> str:
                # For legacy PIN-based pairing (4-digit numeric code)
                # Using a fixed code for simplicity as this is rarely used
                journal.send(f"[agent] RequestPinCode for {device} -> using 0000")
                return "0000"

        @dbus.service.method(AGENT_IFACE, in_signature="o", out_signature="u")
        def RequestPasskey(self, device) -> int:
                # This is called when the agent needs to provide a 6-digit passkey
                # Generate a random passkey between 0 and 999999
                import random
                passkey = random.randint(0, 999999)
                self._generated_passkey = passkey
                journal.send(f"[agent] RequestPasskey for {device} -> GENERATED passkey={passkey:06d}")
                journal.send(f"[agent] *** USER ACTION REQUIRED: Enter passkey {passkey:06d} on the host device ***")
                return passkey

        @dbus.service.method(AGENT_IFACE, in_signature="ou", out_signature="")
        def DisplayPasskey(self, device, passkey: int) -> None:
                # This is called when BlueZ generates a passkey that should be displayed
                journal.send(f"[agent] DisplayPasskey {device} passkey={passkey:06d}")
                journal.send(f"[agent] *** USER ACTION REQUIRED: Verify passkey {passkey:06d} matches on both devices ***")

        @dbus.service.method(AGENT_IFACE, in_signature="os", out_signature="")
        def DisplayPinCode(self, device, pincode: str) -> None:
                # This is called when a PIN code should be displayed (legacy)
                journal.send(f"[agent] DisplayPinCode {device} pincode={pincode}")
                journal.send(f"[agent] *** USER ACTION REQUIRED: Enter PIN {pincode} on the host device ***")

        @dbus.service.method(AGENT_IFACE, in_signature="ou", out_signature="")
        def RequestConfirmation(self, device, passkey: int) -> None:
                # This is called when the user needs to confirm a passkey
                # The passkey is generated by BlueZ and should match on both devices
                journal.send(f"[agent] RequestConfirmation {device} passkey={passkey:06d} -> AUTO-ACCEPT")
                journal.send(f"[agent] *** Passkey {passkey:06d} was auto-confirmed ***")
                # No exception means "yes".

        @dbus.service.method(AGENT_IFACE, in_signature="o", out_signature="")
        def RequestAuthorization(self, device) -> None:
                journal.send(f"[agent] RequestAuthorization {device} -> ACCEPT")

        @dbus.service.method(AGENT_IFACE, in_signature="os", out_signature="")
        def AuthorizeService(self, device, uuid: str) -> None:
                # This is the critical one for HID profile authorization
                journal.send(f"[agent] AuthorizeService device={device} uuid={uuid} -> ACCEPT")

        @dbus.service.method(AGENT_IFACE, in_signature="", out_signature="")
        def Cancel(self) -> None:
                journal.send("[agent] Pairing request canceled")
                self._generated_passkey = None


def main() -> None:
        dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
        bus = dbus.SystemBus()

        adapter_path = _find_adapter(bus)
        if not adapter_path:
                journal.send("[agent] No Bluetooth adapter found, exiting.")
                sys.exit(1)

        # Power on + make discoverable/pairable
        adapter_obj = bus.get_object(BLUEZ_SERVICE_NAME, adapter_path)
        adapter_props = dbus.Interface(adapter_obj, DBUS_PROP_IFACE)

        try:
                adapter_props.Set(ADAPTER_IFACE, "Powered", dbus.Boolean(True))
                adapter_props.Set(ADAPTER_IFACE, "Discoverable", dbus.Boolean(True))
                adapter_props.Set(ADAPTER_IFACE, "Pairable", dbus.Boolean(True))
                journal.send(f"[agent] Adapter {adapter_path} Powered/Discoverable/Pairable = True")
        except Exception as exc:
                journal.send(f"[agent] Failed to tweak adapter properties: {exc}")

        # Register agent
        mgr_obj = bus.get_object(BLUEZ_SERVICE_NAME, "/org/bluez")
        mgr = dbus.Interface(mgr_obj, AGENT_MANAGER_IFACE)

        agent = IprKeyboardAgent(bus)
        mgr.RegisterAgent(AGENT_PATH, "KeyboardOnly")
        mgr.RequestDefaultAgent(AGENT_PATH)
        journal.send("[agent] Registered as default BlueZ agent (KeyboardOnly)")

        loop = GLib.MainLoop()
        try:
                loop.run()
        except KeyboardInterrupt:
                journal.send("[agent] Shutting down")
                try:
                        mgr.UnregisterAgent(AGENT_PATH)
                except Exception:
                        pass


if __name__ == "__main__":
        main()
EOF

chmod +x "$AGENT_PATH"

########################################
# Create systemd service unit
########################################
echo "=== [svc_install_bt_hid_agent] Writing bt_hid_agent.service ==="
cat > /etc/systemd/system/bt_hid_agent.service << 'EOF'
[Unit]
Description=IPR Bluetooth Agent (BlueZ Agent1 for ipr-keyboard)
After=bluetooth.target
Requires=bluetooth.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 /usr/local/bin/bt_hid_agent.py
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload

echo "=== [svc_install_bt_hid_agent] Installation complete ==="
